### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by rubyFeedback** [mananapr/cfiles#1]
Not hugely important, but do you think it may be possible to do another screenshot? Ideally one where the windows could be side by side, and perhaps a black background (to avoid distraction from the application at hand). Again, not hugely important, so feel free to close this issue at any time - I just felt that it may be better to focus on the application itself as such. (It is comparable to screenshots of e. g. midnight commander or htop, if you ask me).

Otherwise nice job - ncurses can be very annoying to have to deal with.

**Comment by mananapr** [comment]
I was thinking of changing the screenshot with a terminal screencast demonstrating the basic functions of the program. What are your thoughts on that?

**Comment by mananapr** [comment]
I have updated the screenshot so I will be closing this thread. Feel free to reopen it if you have any other suggestions
