### ISSUE TITLE
Use XDG paths

### ISSUE THREAD

**Issue by gregf** [mananapr/cfiles#10]
For things like ~/.cache you should use $XDG_CACHE_HOME there is $XDG_CONFIG_HOME etc for different paths  you could be using.

**Comment by mananapr** [comment]
As far as I know `$XDG_CACHE_HOME` is `$HOME/.cache` which is what I am using for `cfiles`. So am I not using XDG paths?

**Comment by gregf** [comment]
You should use the environment variable instead of hard coding the path. The user can change these paths and by using the environment variable you would take the changes the user has made.

**Comment by mananapr** [comment]
For some reason `$XDG_CACHE_HOME` is not set on my system. So I guess I'll make `cfiles` check if `$XDG_CACHE_HOME` is set or not. In case it isn't set, I'll make it use the hard coded path like it is currently using. I'll make these changes in the next commit

**Comment by gregf** [comment]
Yes that is what the XDG spec says to do. Sorry I should have been more clear at the start.

**Comment by mananapr** [comment]
9be9889b0459ddd1bb963578c5d181c8ee9597 Done :)
I'll be closing this issue now but feel free to reopen it in case I missed something
