### ISSUE TITLE
Wrong allocation leads to memory corruption

### ISSUE THREAD

**Issue by cym13** [mananapr/cfiles#11]
# Issue

The function `getNumberOfFiles` is used in a number of places to know how much memory should be allocated. However its return value is never checked (or incorrectly) leading to wrong memory allocations and therefore memory corruptions.

# Bugs

`getNumberOfFiles` is defined to return -1 if opendir fails (for example due to a permission issue).

(following lines are based on 9be9889b0459ddd1bb963578c5d181c8ee9597cd)

## Line 1132:

```c
        // Get number of files in the home directory
        len = getNumberofFiles(dir);

        // Array of all the files in the current directory
        char* directories[len];
```

If len is -1 then the stack allocation messes the stack up. Variable Length Array (VLA) must always have a length strictly greater than 0, otherwise you have undefined behaviour.

## Line 1211:

```c
        // Stores number of files in the child directory
        len_preview = getNumberofFiles(next_dir);
        // Stores files in the child directory
        char** next_directories;
        next_directories = (char **)malloc(len_preview * sizeof(char *));
```

Here we have a similar issue: len_preview may be -1. In that case it is promoted to an unsigned number (size_t) resulting in the allocation of 4294967295 bytes which is a huge value. This should not result directly in a crash since Linux "lies" to the process by making the promise to give it all that space without actually reserving it, but it is definitely a bug.

## Line 1674

```c
        len_scripts = getNumberofFiles(scripts_path);
        if(len_scripts == 0)
        {
            displayAlert("No scripts found!");
            sleep(1);
        }
        else
        {
            char* scripts[len_scripts];
```

Here the output value is checked but that check misses the error value resulting in a negative VLA stack allocation which is undefined behaviour.

# Solution

Always check return values especially if they are meant to indicate errors.

Alternatively avoid VLA as much as possible, they should not be used for large allocations anyway.

**Comment by mananapr** [comment]
I made the relevant changes in eeb46d7. Let me know if they fix this issue

**Comment by cym13** [comment]
The first one still has an issue. VLA are defined only for sizes *strictly greater* than 0, so setting `len` to 0 still results in undefined behaviour.

The second and third issues are untouched by eeb46d7 and therefore still present.

**Comment by mananapr** [comment]
Sorry about the previous commit, 319b7c2 should be good enough.

**Comment by cym13** [comment]
There are still many issues present. The main reason is that, once you hit  an error and know that you are working with a length that has no meaning you should stop using it altogether. On the contrary those lengths are still used many times atferward causing many issues. You way want to start new issues for them since they are no longer allocation issues, but since they are related to the fix of the current issue I could see a case for leaving things as they are.

## Issue 1

The issue with respect to VLA allocation is fixed, however other remain. If `len=-1` line 1137 then line 1163 qsort is called with the argument `nmemb == (size_t)(-1) == 4294967295`, this should touch memory way out of the array.

Later line 1184 we have `for (i=start ; i<len ; i++)` which will result in an integer overflow of `i` which is undefined behaviour since `i` is signed. There is a similar UB via integer overflow line 1770.

## Issue 2

The issue with respect to malloc allocation is fixed. However if `len_preview == -1` then line 1766 there is an undefined behaviour via integer overflow of `i` in the for loop.

## Issue 3

Completely fixed.

**Comment by mananapr** [comment]
Regarding for loops in Issue 1 and 2, if `len` or `len_preview` is -1 and my counter variable starts at a positive value, shouldn't the loop not start at all?

**Comment by cym13** [comment]
Yes, you are perfectly right, I don't know what I was thinking. Sorry.

**Comment by mananapr** [comment]
a3bc4b2 fixes the qsort call in Issue 1. Let me know if this fixes this issue.

**Comment by cym13** [comment]
It fixes it. Keep an eye on it though, since your code is heavy on global variables and variable reuse any small modification may reintroduce similar issues.

**Comment by mananapr** [comment]
Thanks! I'll keep that in mind
