### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by cym13** [mananapr/cfiles#12]
# Issue

Some memory allocated with malloc is never freed: this is a memory leak.

# Bugs

Based on 9be9889b0459ddd1bb963578c5d181c8ee9597cd

## Line 377

```c
    buf = malloc(PATH_MAX);
    while(fgets(buf, PATH_MAX, (FILE*) fp))
    {
        if(buf[0] == bookmark)
        {
            fclose(fp);
            return 1;
```

`buf` is allocated but the function may return without freeing it resulting in a memory leak.

## Line 515

```c
    // Allocate Memory to `temp`
    allocSize = snprintf(NULL,0,"%s", filepath);
    temp = malloc(allocSize+1);
    snprintf(temp, allocSize+1, "%s", filepath);
    temp[strlen(temp)]='\0';
    if(f == NULL)
    {
        return 0;
    }
```

`temp` is allocated but the function may return without freeing it resulting in a memory leak.

# Solution

Free any allocated memory before returning from the function that defined that variable.

**Comment by mananapr** [comment]
eeb46d7 fixes this. I'll be closing this issue but feel free to reopen it in case I missed something
