### ISSUE TITLE
Memory corruption

### ISSUE THREAD

**Issue by cym13** [mananapr/cfiles#13]
# Issue

There is an out-of-bound read from the directories buffer line 1330 (rev adf61b20f9b4bd5c4249cfa05cf9d44e7fe06739).

# Analysis

```c
// Line 1253
len = getNumberofFiles(dir);                  // If len == 0

// Set temp_len to 1 if `len` is less than 0
if(len <= 0)
    temp_len = 1;
else
    temp_len = len;

// ...
// Line 1284
if(selection > len-1)                         // If selection==0, >(0-1) is true
{
    selection = len-1;                        // selection = -1;
}

// ...
// Line 1330
// Copy of directories[-1] into selected_files. That read is out of bound.
snprintf(selected_file,NAME_MAX,"%s",directories[selection]);
```

# Local fix

Do not set selection to -1.

# Global fix

* Avoid using global variables
* As soon as the length is known invalid, stop using it and return

**Comment by mananapr** [comment]
127b8d8 fixes this. feel free to re-open if there is still something wrong

**Comment by cym13** [comment]
Hi,

# Issue

This should be reoppened because it's not fixed.

Right now we have this line 1439
```c
snprintf(selected_file,NAME_MAX,"%s",directories[selection]);
```

But if the directory is empty then selection will be 0 by the time we get to that line, and directories will have been allocated this way line 1367:

```c
// Get number of files in the home directory
len = getNumberofFiles(dir);

// Set temp_len to 1 if `len` is less than 0
if(len <= 0)
    temp_len = 1;
else
    temp_len = len;

// Array of all the files in the current directory
char* directories[temp_len];
```
This means that although it was allocated with a length of 1 (and thus should contain at least 1 record) this first record is actually an uninitialized pointer to a non-existing string that we are trying to copy into `selected_file` through `directories[selection]`. This is an outbound read and it should segfault.

# Fix

We are starting to see the limits of spaghetti code that reuses lots of variables and does not stop using variables once it is known that their value is not valid in any way. I'm not sure what the fix should be here.

A cleaner approach would be to have two separate ways to deal with directories that have content and those that are empty and never ever mix the two by pretending that a -1 is a 1 or a 0.

**Comment by mananapr** [comment]
If I allocate the first entry in `directories` as a string "Empty" (in case `len` is 0) will that solve this problem?

**Comment by cym13** [comment]
It should solve this specific issue indeed.

**Comment by mananapr** [comment]
Does b37b3ce solve it?
I plan to refactor the code after fixing all the bugs first

**Comment by cym13** [comment]
Looks good to me from a memory point of view.

**Comment by mananapr** [comment]
I'll be closing this then. Thanks!
