### ISSUE TITLE
[Improvement] Displaying binary files

### ISSUE THREAD

**Issue by LeJoW** [mananapr/cfiles#15]
The binary files are displayed by an ASCII representation. I think it would be usefull to display in hex format, wouldn't it (like `most` does) ?

**Comment by mananapr** [comment]
I plan to replace the ASCII preview with just some text mentioning that the selection is a binary file in the next release. Will this be good or a hex preview would be better?

**Comment by LeJoW** [comment]
If the speed of an hex preview is good, it would be better for me.

**Comment by mananapr** [comment]
Is the output from `hexdump` good enough for preview?

**Comment by mananapr** [comment]
Binary previews are shown in hex format in the latest revision. You can press <kbd>I</kbd> if you want to scroll through the whole hex dump.
I'll be closing this issue but feel free to re-open it If you want to add something or have any other questions
