### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [mananapr/cfiles#23]
Would you like to add more error handling for return values from functions like the following?
- [fopen](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream.") ⇒ [displayBookmarks](https://github.com/mananapr/cfiles/blob/72771db7192fdbb916e81c53d241732101bddb9f/cf.c#L351)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [init](https://github.com/mananapr/cfiles/blob/72771db7192fdbb916e81c53d241732101bddb9f/cf.c#L150)

**Comment by mananapr** [comment]
I added error checks in  rev b6c0869. Let me know if I missed something

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for [this software](https://github.com/mananapr/cfiles/blob/b6c08690bd065f08c6692e408820ece8ac26a8c4/cf.c#L577 "Update candidate: addBookmark()")?

**Comment by mananapr** [comment]
I am new to C and don't know much about the various tools devs use but I was recommended valgrind for static code analysis.
Also I made some fixes in rev 513ad4b

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "Software development with AspectC++?")?
* How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?
