### ISSUE TITLE
Does img preview in left window is default setting?

### ISSUE THREAD

**Issue by roachsinai** [mananapr/cfiles#25]
I got image preview at left window, which is different with README.md.

![image](https://user-images.githubusercontent.com/9500049/54523314-31c87700-49aa-11e9-84ee-9e94b040c50f.png)

**Comment by roachsinai** [comment]
I'm using `w3m`.

**Comment by mananapr** [comment]
If you are using `w3m` you'll have to change `FONTH` and `FONTW` in the `displayimg` script

**Comment by roachsinai** [comment]
Okay. I've tested, and

```
FONTH=21 # Size of one terminal row
FONTW=11 # Size of one terminal column
```

is proper value for me.

`Yakuake`:

![image](https://user-images.githubusercontent.com/9500049/54524567-40645d80-49ad-11e9-9198-d23c36328af2.png)

`Konsole`:

![image](https://user-images.githubusercontent.com/9500049/54524653-7d305480-49ad-11e9-9c80-63551ab19f05.png)

**Comment by roachsinai** [comment]
Picture not show in `cfiles` after latest upgrade.

The update process:

1. Set using `clearimg` 和`displayimg` in `cfiles.h`.
2. Set `FONTH=21` and `FONTW=11` in `/usr/local/bin/displayimg`.

OS: Manjaro.

**Comment by mananapr** [comment]
The file paths were changed in the latest upgrade to match with the Arch Linux packaging guidlines. The old version of cfiles installed the scripts and the main binary at `/usr/local/bin` but the latest version installs the main binary at `/usr/bin` and the scripts at `/usr/share/cfiles/scripts`. So make sure the paths in the config and the paths of the scripts are matching.

I would recommend completely uninstalling `cfiles`, then manually removing files from the old and new locations (in case they still exist) and then start with a fresh install. Let me know if you still encounter any issues.

**Comment by roachsinai** [comment]
Sorry that I chaged the PKGBUILD for my situation. Now worked well. Thanks!
