### ISSUE TITLE
how to use script in user_scripts?

### ISSUE THREAD

**Issue by roachsinai** [mananapr/cfiles#26]
As there is not shortkey defined about them in [cfiles.h](https://github.com/mananapr/cfiles/blob/master/config.h).

**Comment by mananapr** [comment]
You have to put your scripts in `~/.config/cfiles/scripts`. Then press <kbd>P</kbd> in `cfiles` to use the scripts.

**Comment by roachsinai** [comment]
So sorry that I missed it. Thanks!
