### ISSUE TITLE
cfiles preview bash script get hex code.

### ISSUE THREAD

**Issue by roachsinai** [mananapr/cfiles#27]
As `xdg-mime` output `application` for bash script and tar file,

```
hmank ~/./y/cfiles master > touch tt.sh && xdg-mime query filetype tt.sh
application/x-shellscript
hmank ~/./y/cfiles master > xdg-mime query filetype tt.py
text/x-python
hmank ~/./y/cfiles master > touch tt.tar.xz && xdg-mime query filetype tt.tar.xz
application/x-xz-compressed-tar
```

Maybe should use `application/x-executable` and `application/x-sharedlib` to check whether file is a binary?

```
hmank ~/./y/cfiles master > xdg-mime query filetype /usr/bin/zsh
application/x-sharedlib
hmank ~/./y/cfiles master > xdg-mime query filetype /usr/bin/firefox
application/x-shellscript
hmank ~/./y/cfiles master > 
```

**Comment by mananapr** [comment]
You are saying `cfiles` should only display hex previews for `application/x-executable` and `application/x-sharedlib` filetypes right?

**Comment by mananapr** [comment]
yes you are right. i'll start working on it

**Comment by mananapr** [comment]
I have made the relevant changes and updated the AUR package as well. Let me know if there are some other bugs. Thanks!
