### ISSUE TITLE
Make navigation keys configurable instead of hardcoded

### ISSUE THREAD

**Issue by Maciej-Motyka** [mananapr/cfiles#30]
Users of non-qwerty keyboard layouts often want to change the keybindings to preserve the physical positions on the keyboard. In cfiles the navigation keys are hardcoded preventing this.

I use Dvorak. After changing all configurable keybindings in `config.h`, I get error when compiling.

```bash
me@computer:/usr/local/src/cfiles$ make  
gcc -I. -Wall cf.c -o cfiles -lncursesw
In file included from cf.c:28:
cf.c: In function ‘main’:
cf.c:2473:13: error: duplicate case value
             case KEY_MV:
             ^~~~
cf.c:2094:13: note: previously used here
             case 'k':
             ^~~~
cf.c:2630:13: error: duplicate case value
             case KEY_SCRIPT:
             ^~~~
cf.c:2106:13: note: previously used here
             case 'l':
             ^~~~
make: *** [Makefile:10: all] Error 1
```
I discovered that the hjkl keys are hardcoded in the cf.c file, to serve as the navigation keys. On Dvorak layout the analogous keys in the right hand home row are dhnt. In order to remap them and resolve the conflicts I edited these four lines:

```diff
        // Keybindings
        switch( ch = wgetch(current_win) )
        {
            // Go up
            case KEY_UP:
-           case 'k':
+           case 't':
                scrollUp();
                break;

            // Go down
            case KEY_DOWN:
-           case 'j':
+           case 'h':
                scrollDown();
                break;

            // Go to child directory or open file
            case KEY_RIGHT:
-           case 'l':
+           case 'n':
            case '\n':
                goForward();
                break;

            // Go up a directory
            case KEY_LEFT:
-           case 'h':
+           case 'd':
                goBack();
                break;
```
It is doable, but requires unnecessary effort. Exposing the nav keys to user via config file will not clutter it and will save time and effort for non-qwerty users who want to preserve the physical positions of the keys.

**Comment by mananapr** [comment]
Implemented in a62e95e

Let me know if you encounter any bugs. Thanks!
