### ISSUE TITLE
Use SHELL env variable instead of hardcoding bash

### ISSUE THREAD

**Issue by aonemd** [mananapr/cfiles#33]
Hello, 

I noticed that when I use the key mapping `S` to open a shell session, cfiles opens a `bash` shell instead of my default shell, `zsh`. 

I suggest we change this to use the `SHELL` environment variable instead. Thanks!

**Comment by mananapr** [comment]
I implemented this in  rev. b816801. Let me know if you encounter any bugs. Thanks!
