### ISSUE TITLE
EDITOR (Vim) prints `Command terminated` when opening a file

### ISSUE THREAD

**Issue by aonemd** [mananapr/cfiles#34]
When I open a file through cfiles, in my EDITOR (Vim), it prints the following message:

![screenshot_2019-05-13_00:36:24](https://user-images.githubusercontent.com/16504838/57588817-71c75880-751a-11e9-837d-23748985d519.png)

before showing the file content. 

I know the issue has to do with Vim in particular (since it doesn't occur with nano for example), but is there some program/command that is run before Vim is run so that this message is printed?

**Comment by mananapr** [comment]
try doing [this](https://stackoverflow.com/questions/22980176/how-to-debug-vimrc-on-command-terminated)?

**Comment by aonemd** [comment]
Thanks for link! After some debugging, I wen to check my plugins and it turns out, this is actually caused by [tpope/vim-fugitive](https://github.com/tpope/vim-fugitive). So I'm closing this now. Apologies if i caused any inconvenience.
