### ISSUE TITLE
Feature request: PDF preview

### ISSUE THREAD

**Issue by cbosoft** [mananapr/cfiles#37]
It would be great if PDF preview could be added in. I liked to use `ranger` to skim through my documents folder (stuffed with PDFs), and I'd like to do the same with `cfiles`. 

I've sort of got this working in a hack-y way: changing the `displayimg` script to check for PDFs and convert to jpg for preview using ghostscript. This means that text preview would not work if ghostscript is not available.

```bash
PDFPREV=/tmp/pdf_thumb.jpg

IMGEXT="${FILENAME##*.}"

case $IMGEXT in
  pdf|PDF)
    command -v gs &> /dev/null || exit 1
    gs -dNOPAUSE -dBATCH -sDEVICE=jpeg -sOoutputFile=$PDFPREV -dLastPage=1 "$FILENAME" &>/dev/null
    FILENAME=$PDFPREV
    ;;
esac
```

I dunno if there's a better way?

**Comment by mananapr** [comment]
are you experiencing any lags with your method? AFAIK ranger uses `pdftotext` for pdf previews so I'll look into it too

**Comment by cbosoft** [comment]
Ranger does use `pdftotext` as default, but there's a commented out code block in `scope.sh` in ranger which converts the PDF to image. Looking at it now, `ranger` uses `pdftoppm` rather than `ghostscript`.

It doesn't really lag, ghostscript is quite fast. [video](https://i.imgur.com/MRENvMJ.mp4)

**Comment by mananapr** [comment]
Check out the latest release and let me know if you encounter any bugs. I tested it on some small PDF documents and it was responsive. Haven't yet tried with bigger sized PDFs

**Comment by cbosoft** [comment]
I think `pdftoppm` is somehow inconsistent about the numbering it uses:

![screenshot of ls /tmp/prev*](https://i.imgur.com/aYXzwye.png)

I (mostly) couldn't get a PDF preview. The code expects an image preview to be generated with the name "prev-001.jpg", right? My `pdftoppm` gives "prev-01.jpg" sometimes:

![screenshot of pdftoppm output](https://i.imgur.com/kMpBjpM.png)

However adding the `-singlefile` option removes the numbering from the output file, resulting in only the extension ".jpg" being added:

![screenshot of pdftoppm output2](https://i.imgur.com/DXhhibw.png)

I wonder why the numbering is sometimes different?

Thanks for putting in the time to add this feature :) However, it's a bit slow, and for some reason, I'm getting the same PDF preview for different files: [video](https://i.imgur.com/NRzgdDk.mp4)

**Comment by mananapr** [comment]
Checkout the latest commit. I used the `-singlefile` option and now I am not getting same previews for different files. The speed is okay for small PDFs but it can take 1-2s for 40+mb PDFs. For this reason I have made it optional in the config. Try the latest commit and let me know how it works for you

**Comment by cbosoft** [comment]
Perfect! Thank you :)
