### ISSUE TITLE
Archive preview

### ISSUE THREAD

**Issue by sikmir** [mananapr/cfiles#38]
Currently only `.zip, .rar, .cbr, .cbz` archives are displayed:
https://github.com/mananapr/cfiles/blob/33f9c0a1605f3b8ac8f7378e6edb6c63185a7805/cf.c#L1291-L1292
Could you please add preview support for `.tar.bz2, .tar.gz, .tar.xz`, etc?

**Comment by mananapr** [comment]
I have added support for them in the latest version. Thanks!
