### ISSUE TITLE
Code execution

### ISSUE THREAD

**Issue by cym13** [mananapr/cfiles#4]
# The issue

There are arbitrary code execution vulnerabilities due to unproper handling of filenames.
If a filename contains a shell command it will be executed when the file is opened.

# How to reproduce

Create a file with a shell command, here a command that creates another file:

    $ touch '; touch test'

Navigate that directory with cfiles and try to open the file. The command will be executed.

# The bug

In openFiles a string containing a shell command is built from the filename before being executed with system(). Since filenames may contain shell commands that are not escaped this results in code execution.

# The risk

If user A tries to open a file created by user B that contains a shell command it will be executed by user A's rights. This is a form of privilege escalation.

# Other locations

There are multiple other places where system() is used in an unsafe way. All of them appear vulnerable one way or another. Also popen() is another function that should be used with care.

# The fix

- Avoid system() whenever possible, use execl or execve instead (see https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152177 for example). They are more secure since your are not building a string, your are passing a list of arguments to the process directly.

- If you still want to build a string be sure to escape all arguments, so you should force single quotes and escape any single quote in the argument. Warning though, escaping is a good thing but it's hard to do right.

**Comment by cym13** [comment]
You can use pipes directly in C (those are standard POSIX functions after all), but it's honnestly a bit cumbersome. You might prefer to go the escaping way in this case. On the other hand, since this all seems to be a learning project it might be a good occasion to get your hands dirty.

**Comment by mananapr** [comment]
I removed all the `system()` calls and replaced them with `fork()` plus `execl()` in  be4124c. Let me know if there are some other vulnerabilities.

**Comment by cym13** [comment]
1) Hardcoding the paths isn't a good idea either, there is no guaranteed that vim is in /usr/bin (or that that's the version of vim that I expect to call). I know I'm the one that recommended to use `execl`, but I should have said `execlp` which searches the PATH for the executable, so that

```c
    execl("/usr/bin/vim", filename, (char*)NULL);
```

Becomes

```c
    execlp("vim", filename, (char*)NULL);
```

2) This one I love. There is no shell injection since you use execl which is good. However it is possible to inject sed command, and sed can execute shell commands, so there is still a code execution possible:

```c
    // Allocate Memory to `cmd`
    allocSize = snprintf(NULL, 0, "%s", "/usr/bin/sed");
    cmd = malloc(allocSize+1);
    snprintf(cmd, allocSize+1, "%s", "/usr/bin/sed");

    // Allocate Memory to `arg`
    allocSize = snprintf(NULL, 0, "\\|^%s|d", filepath);
    arg = malloc(allocSize + 1);
    snprintf(arg, allocSize+1, "\\|^%s|d", filepath);

    // Create a child process to run command
    pid_t pid;
    pid = fork();
    if( pid == 0 )
    {
        execl(cmd, cmd, "-i", arg, clipboard_path, (char *)0);
        exit(1);
    }
```

If a file is named `|p;e id\n;|^` (a strange but perfectly valid name), the sed command becomes `sed "\\|^|p;e id\n;|^|d"` which will execute the shell command `id`. The only solution is to escape the path provided to sed (or not use sed).

3) Similarly there is a shell injection reintroduced here:

```c
                snprintf(temp_dir, allocSize+1, "cd %s && bash", dir);
                // ...
                if( pid == 0 )
                {
                    execl("/usr/bin/bash", "bash", "-c", temp_dir, (char *)0);
```

If the current path contains a shell command it will be executed by bash since that's explicitely what you're asking for. I'd rather do something like:

```c
    chdir("/tmp/");
    execlp("bash", "bash", "-i");
```

Since you're in a child process anyway it won't impact the main process.

4) You fixed calls to system, but no those to popen() which have the exact same issues when the argument is build from user inputs. Those result in shell injections.

**Comment by mananapr** [comment]
First of all thank you fo much for reviewing my code! I have been getting a lot of work from my uni so I couldn't work on cfiles for some time.
I worked on the issues you mentioned in 127b8d8.

- I started using `execlp` instead of `execl`

- Stopped using `sed` for de-selecting a file

- Used your approach for opening a bash shell

- I stopped using `popen`

Let me know if these changes fix the issues. Thanks again!

**Comment by cym13** [comment]
Looks good to me regarding code execution.

However for your refactoring I'd replace writting to a temporary file in a process just to read it from the other by inter-process communication. If you're not familiar with it you may want to read [this article](http://www.microhowto.info/howto/capture_the_output_of_a_child_process_in_c.html). It's similar to what you do (fork+dup+read/write) except you use a pipe() to get file descriptors to write to without needing an actual file on disk.

Also, I don't really like programming but finding security flaws in software is my job so that's about the only way for me to contribute to free software projets, especially when there isn't any financial backup to get a professional audit. So I'll pester you some more, don't worry, it's good training for me too ;)

**Comment by mananapr** [comment]
Thanks :)
