### ISSUE TITLE
Please use $(prefix) supplied to make instead of "/usr"

### ISSUE THREAD

**Issue by yurivict** [mananapr/cfiles#41]
```config.h``` has it hardcoded: ```"/usr/share/cfiles/scripts/displayimg_uberzug"```

You need to use the prefix value supplied to the makefile, so that it would be defined in one place.

**Comment by mananapr** [comment]
The values in `config.h` are defined for those who are manually compiling it from the default `Makefile`. But while making packages, it may be necessary to patch the config for some systems. For eg for the macOS brew install script [here](), I had to change location of scripts to suit macOS.
Hence, it would be better if you can patch the `config.h` like you are patching the scripts and the Makefile
