### ISSUE TITLE
Please use $XDG_CONFIG_HOME for scripts and bookmarks

### ISSUE THREAD

**Issue by fliggsos** [mananapr/cfiles#43]
cfiles is a great little tool, just one thing disturbes me (at the moment):
you use the $XDG_CACHE_HOME for storing bookmarks and scripts.
Cache is normally only temporarily, so on my system:
$XDG_CACHE_HOME is mounted  "tmpfs" in ram to speed up some things and conserve sdd usage.
Is it possible to move bookmarks and scripts to
$XDG_CONFIG_HOME, eg ~/.config/cfiles ?
Thanks a lot,
Fliggs

**Comment by mananapr** [comment]
I have been planning to that for a long time so thanks for opening this isuue. I have added this in the latest release v1.8. Let me know if you encounter any bugs
