### ISSUE TITLE
Image preview loads slow compared to ranger

### ISSUE THREAD

**Issue by astier** [mananapr/cfiles#45]
Hi. I like cfiles. Thx. Generally the image preview is better then in ranger because it works nice with tmux. The images are always on the right place and do not disappear when changing panes. However, the images load notably slower in cfiles than in ranger. Since cfiles goal is to be fast I think this is something that should be fixed.  Also it bothers me when I scroll through many images.

**Comment by mananapr** [comment]
I presume it's because you are using the `ueberzug` backend for image previews? If that's the case, then nothing can be done as `ueberzug` is slower when compared to `w3mimg` which is what ranger uses. You can try using the `w3m` backend with `cfiles` but it doesn't works nicely for me atleast
