### ISSUE TITLE
enhancement: remove bookmark shortcut

### ISSUE THREAD

**Issue by maciejmotyka** [mananapr/cfiles#48]
If I am not mistaken deleting a bookmark is currently performed by deleting it from `$XDG_CACHE_HOME/cfiles/bookmarks`. However on my system `echo $XDG_CACHE_HOME` returns nothing. I am also unable to determine where the bookmark info is stored in such case. `fzf -e -q cfiles` or `fzf -e -q bookmarks` doesn't return anything that would catch my eye.
I've read through the `cf.c` code but my C knowledge is too limited to figure out the alternative location.

Due to this difficulty, but mostly because I think that it would make for a better user experience, I suggest adding a possibility to remove unwanted bookmarks directly from `cfiles`.
In Vim it's done via its command line, which is not how `cfiles` operates, so I think it will have to function similarly to adding a bookmark, i.e. `<KEY_DELBOOKMARK><BOOKMARK>` .

**Comment by mananapr** [comment]
I've added this in the latest commit. If you press `E`, it will open your bookmarks in your preferred editor and you can edit them as you wish.

**Comment by maciejmotyka** [comment]
Works like a charm. Thank you!
