### ISSUE TITLE
Use EDITOR environment variable instead of hardcoding vim

### ISSUE THREAD

**Issue by andrewpillar** [mananapr/cfiles#7]
It would perhaps be best if you made a call to [getenv](http://pubs.opengroup.org/onlinepubs/009695399/functions/getenv.html) and passed it the `EDITOR` environment variable for opening up text files from within this file-manager. This can provide more flexibility for end users who would prefer to use another text editor other than `vim`.

For example:

```c
char cmd[250];
sprintf(cmd,"%s %s", getenv("EDITOR"), filepath);
```

I've just taken some of the pre-existing code from the main file, though you should most definitely revise this as it is prone to buffer-overflow errors/attacks as others have mentioned.

Nonetheless I think this is a pretty cool project, and definitely a good learning experience for someone who wants to pick up C, and familiarise themselves with the language.

**Comment by mananapr** [comment]
I'll make the changes in the next commit. Thanks for the suggestion

**Comment by andrewpillar** [comment]
No problem, I'd also suggest checking to see if the environment variable is set in the first place, and if not then fallback to `vim`.

**Comment by mananapr** [comment]
The latest commit adds this functionality so I'll be closing this issue. Feel free to reopen it in case it is not working as expected
