### ISSUE TITLE
don't hardcode path's

### ISSUE THREAD

**Issue by gregf** [mananapr/cfiles#8]
It would be nice to not hardcode path's in cf.c and let the users path do the work. At the very least make paths configurable, because most of these locations are different for us BSD users.

**Comment by mananapr** [comment]
I can add an option for user's to define their own paths in config.h. How does that sound?
Just to be clear, by paths you mean the Trash and Cache paths right?

**Comment by gregf** [comment]
Trash & Cache paths are fine under BSD. It's the paths to programs like w3mimgdisplay.

**Comment by mananapr** [comment]
Ah, got it. I'll make the changes in the next commit

**Comment by mananapr** [comment]
I have completely changed how image previews work with the latest commit. That fixes the terminal flickering issue and the issue you mentioned in this thread.
Feel free to reopen this thread if I missed something else.
